redirectsOrigin = "config"
plugins = []
functionsDirectory = "F:\\nodeJS\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "F:\\nodeJS\\netlify"
publishOrigin = "default"
functions = "F:\\nodeJS\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]